spring:
  application:
    name: springBootAssembly
  profiles:
    active: dev
  redis:
      timeout: 3000  #连接超时时间
      jedis.pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5    # 连接池中的最大空闲连接
        min-idle: 2    # 连接池中的最小空闲连接
      host: 127.0.0.1
      port: 6379
      database: 0
      password: root
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qa_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
server:
  port: 8080
